### ISSUE TITLE
Does not compile - what I did wrong?

### ISSUE THREAD

**Issue by ignatandrei** [Elskom/IDisposableGenerator#35]
# Issue Details
Try to make an example for the list of RSCG from https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

**Describe the bug**
I have added the nuget package
It does not find the attribute [GenerateDispose(true)]  - compile error.

See the code at https://github.com/ignatandrei/RSCG_Examples/tree/119-idisposablegenerator , folder <RSCG_Examples>\v2\rscg_examples\IDisposableGenerator\src\IDisp.sln

.

**To Reproduce**

1. Clone branch https://github.com/ignatandrei/RSCG_Examples/tree/119-idisposablegenerator 
2. Open <RSCG_Examples>\v2\rscg_examples\IDisposableGenerator\src\IDisp.sln

3. Compile.
4. Error occurs  error CS0246: The type or namespace name 'GenerateDisposeAttribute' could not be found 

**Expected behavior**
Can generate code

**Actual behavior**
Does not compile

*Version used**
```xml
<PackageReference Include="IDisposableGenerator" Version="1.1.1">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
	 
```
**Additional context**
Please help

**Comment by AraHaan** [comment]
That is odd, according to this code it should be working: https://github.com/Elskom/IDisposableGenerator/blob/main/src/IDisposableGenerator.CSharp/IDisposableGenerator.cs#L45-L50

**Comment by ignatandrei** [comment]
It is now working (maybe it was > number of chars for folders in Windows?)

https://ignatandrei.github.io/RSCG_Examples/v2/docs/IDisposableGenerator

Thanks
