### ISSUE TITLE
v1.1.0 Roadmap

### ISSUE THREAD

**Issue by AraHaan** [Elskom/IDisposableGenerator#6]
## Roadmap for v1.1.0

| Issue | Status |
|:-----:|:------:|
| [Source Generate the attributes unconditionally (Post Init).](https://github.com/Elskom/IDisposableGenerator/issues/1) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/8) |
| [Rename SetNullOnDispose to NullOnDispose](https://github.com/Elskom/IDisposableGenerator/issues/2) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/22) |
| [Ensure that all generated code use file scoped namespaces and global usings on C# 10 or newer.](https://github.com/Elskom/IDisposableGenerator/issues/3) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/16) |
| [Migrate to using IIncrementalGenerator (Source Generator V2 APIs)](https://github.com/Elskom/IDisposableGenerator/issues/4) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/21) |
| [Remove Roslyn package dependencies from generator nuget package file.](https://github.com/Elskom/IDisposableGenerator/issues/7) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/8) |
| [Place generator files in analyzers\dotnet\cs instead of analyzers\cs.](https://github.com/Elskom/IDisposableGenerator/issues/12) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/17) |
| [Add Visual Basic source generator.](https://github.com/Elskom/IDisposableGenerator/issues/25) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/26) |
| [Allow multiple WorkItems in generator.](https://github.com/Elskom/IDisposableGenerator/issues/19) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/20) |

## Future
- #5
  - This issue would be for in the future, to migrate from github actions to the workflow normally used by the .NET Foundation member projects (when this project becomes a full member in the future)
- Set up arcade versioning (and set the generator project's ``IsShipping`` to true, but set test project to NonShipping).
- Maybe utilize arcade testing as well?
- use common engineering directory that normally exists for .NET Foundation projects.
- Migrate to Issue Forms.

**Comment by AraHaan** [comment]
## Roadmap for v1.1.1 Servicing


| Issue | Status |
|:-----:|:------:|
| [KeepOpen is improperly handled in the generated code.](https://github.com/Elskom/IDisposableGenerator/issues/31) | [Completed](https://github.com/Elskom/IDisposableGenerator/pull/32) |

**Comment by Rekkonnect** [comment]
Is this ready for closing since 1.1.1 has been released?

**Comment by AraHaan** [comment]
I think so yeah.
